---
# Main playbook file

- hosts: asennus
  remote_user: root
  vars:
    datapath_url: https://packages.kopla.jyu.fi/tilatal/VisionInstall-7.6.0.124.tar.gz
    blackmagic_url: https://packages.kopla.jyu.fi/tilatal/desktopvideo_10.2a5_amd64.deb 
    galicaster_url: https://packages.kopla.jyu.fi/tilatal/galicaster-1.4.1-1.8JYU.tar.gz
  tasks:
    - include: packages.yml
    - include: drivers.yml
    - include: services.yml
    - include: application.yml
    - include: mediadisk.yml
